DROP TABLE IF EXISTS APPLIANCES;

CREATE TABLE APPLIANCES(
SERIALNUMBER SERIAL,
BRAND VARCHAR(30) NOT NULL,
MODEL VARCHAR(30) NOT NULL,
STATUS VARCHAR(30) NOT NULL,
DATE DATE DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (SERIALNUMBER)
);

INSERT INTO APPLIANCES(BRAND,MODEL,STATUS,DATE) VALUES('samsung','S10','active',NOW());
INSERT INTO APPLIANCES(BRAND,MODEL,STATUS,DATE) VALUES('samsung','S20','active',NOW());
INSERT INTO APPLIANCES(BRAND,MODEL,STATUS,DATE) VALUES('LG','L10','inactive',NOW());
INSERT INTO APPLIANCES(BRAND,MODEL,STATUS,DATE) VALUES('HITACHI','H10','active',NOW());
INSERT INTO APPLIANCES(BRAND,MODEL,STATUS,DATE) VALUES('samsung','S910','inactive',NOW());
INSERT INTO APPLIANCES(BRAND,MODEL,STATUS,DATE) VALUES('sony','SS10','active',NOW());
INSERT INTO APPLIANCES(BRAND,MODEL,STATUS,DATE) VALUES('OGENERAL','O10','active',NOW());

